Fix date comparisons during coupon activations
Andre0512/lidl-plus pull request #11
Opened 2023-11-12 10:53 UTC by 1-Byte

Fix the following error on Python 3.11:
```text
Traceback (most recent call last):
  File ".venv/bin/lidl-plus", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "lidlplus/__main__.py", line 162, in start
    main()
  File "lidlplus/__main__.py", line 156, in main
    activate_coupons(args)
  File "lidlplus/__main__.py", line 138, in activate_coupons
    if datetime.fromisoformat(coupon["startValidityDate"]) > datetime.now():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
```

2023-11-19 21:45 UTC, Andre0512 requested changes
Hi, I would prefer to use `datetime.utcnow()` here. It's a bit shorter and doesn't need the import.

2023-11-20 14:25 UTC, 1-Byte commented
Hi, this would not fix the issue because [`datetime.utcnow()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) returns a naive datetime (and the comparison would be off). `fromisoformat()` needs a timezone-aware date to compare against.

2023-11-20 15:44 UTC, Andre0512 approved these changes

2023-11-20 15:45 UTC, Andre0512 commented
That's a good point I didn't consider... thank you! :smiley:

2023-11-20 15:45 UTC, merged